export const SAVE_USER = 'SAVE_USER';
export const SAVE_GROUP_DESTINATION = 'SAVE_GROUP_DESTINATION';
export const SAVE_GROUP_TRAVELMODE = 'SAVE_GROUP_TRAVELMODE';
export const SAVE_GROUP_ACCOMMODATION = 'SAVE_GROUP_ACCOMMODATION';
export const SAVE_GROUP_NUMBEROFPEOPLE = 'SAVE_GROUP_NUMBEROFPEOPLE';
export const SAVE_GROUP_MINIMUMAGE = 'SAVE_GROUP_MINIMUMAGE';
export const SAVE_GROUP_MAXIMUMAGE = 'SAVE_GROUP_MAXIMUMAGE';
export const SAVE_GROUP_TRAVELWITHCHILDREN = 'SAVE_GROUP_TRAVELWITHCHILDREN';
export const SAVE_GROUP_TRAVELWITHPETS = 'SAVE_GROUP_TRAVELWITHPETS';
export const SAVE_GROUP_DESCRIPTION = 'SAVE_GROUP_DESCRIPTION';
export const SAVE_GROUP_COVERPHOTO = 'SAVE_GROUP_COVERPHOTO';
export const SAVE_GROUP_GALLERY = 'SAVE_GROUP_GALLERY';
export const SAVE_GROUP_BUDGET = 'SAVE_GROUP_BUDGET';
export const SAVE_GROUP_DESTINATION_PLACE_DATA = 'SAVE_GROUP_DESTINATION_PLACE_DATA';


