export const SAVE_USER = 'SAVE_USER';
export const GET_USER = 'GET_USER';
export const SAVE_GROUP_DESTINATION = 'SAVE_GROUP_DESTINATION';
export const SAVE_GROUP_TRAVELMODE = 'SAVE_GROUP_TRAVELMODE';
export const SAVE_GROUP_ACCOMMODATION = 'SAVE_GROUP_ACCOMMODATION';
export const SAVE_GROUP_NUMBEROFPEOPLE = 'SAVE_GROUP_NUMBEROFPEOPLE';
export const SAVE_GROUP_MINIMUMAGE = 'SAVE_GROUP_MINIMUMAGE';
export const SAVE_GROUP_MAXIMUMAGE = 'SAVE_GROUP_MAXIMUMAGE';
export const SAVE_GROUP_TRAVELWITHCHILDREN = 'SAVE_GROUP_TRAVELWITHCHILDREN';
export const SAVE_GROUP_TRAVELWITHPETS = 'SAVE_GROUP_TRAVELWITHPETS';
export const SAVE_GROUP_DESCRIPTION = 'SAVE_GROUP_DESCRIPTION';
export const SAVE_GROUP_COVERPHOTO = 'SAVE_GROUP_COVERPHOTO';
export const SAVE_GROUP_GALLERY = 'SAVE_GROUP_GALLERY';
export const SAVE_GROUP_BUDGET = 'SAVE_GROUP_BUDGET';
export const SAVE_GROUP_GENRE = 'SAVE_GROUP_GENRE';
export const SAVE_GROUP_DATES = 'SAVE_GROUP_DATES';
export const SAVE_GROUP_STARTING_TRAVEL = 'SAVE_GROUP_STARTING_TRAVEL';
export const LOAD_GROUP_BY_USER_SUCCESS = 'LOAD_GROUP_BY_USER_SUCCESS';
export const LOAD_GROUP_BY_USER_FAIL = 'LOAD_GROUP_BY_USER_FAIL';
export const LOAD_GROUP_BY_USER_REQUEST = 'LOAD_GROUP_BY_USER_REQUEST';
export const LOAD_GROUPS_REQUEST = 'LOAD_GROUPS_REQUEST';
export const LOAD_GROUPS_SUCCESS = 'LOAD_GROUPS_SUCCESS';
export const LOAD_GROUPS_FAIL = 'LOAD_GROUPS_FAIL';
export const LOAD_GROUP_BY_ID_REQUEST = 'LOAD_GROUP_BY_ID_REQUEST';
export const LOAD_GROUP_BY_ID_SUCCESS = 'LOAD_GROUP_BY_ID_SUCCESS';
export const LOAD_GROUP_BY_ID_FAIL = 'LOAD_GROUP_BY_ID_FAIL';
export const REQUEST_TO_JOIN_GROUP_REQUEST = 'REQUEST_TO_JOIN_GROUP_REQUEST';
export const REQUEST_TO_JOIN_GROUP_SUCCESS = 'REQUEST_TO_JOIN_GROUP_SUCCESS';
export const REQUEST_TO_JOIN_GROUP_FAIL = 'REQUEST_TO_JOIN_GROUP_FAIL';
export const LOAD_JOIN_REQUESTS_REQUEST = 'LOAD_JOIN_REQUESTS_REQUEST';
export const LOAD_JOIN_REQUESTS_SUCCESS = 'LOAD_JOIN_REQUESTS_SUCCESS';
export const LOAD_JOIN_REQUESTS_FAIL = 'LOAD_JOIN_REQUESTS_FAIL';
export const SAVE_JOIN_MESSAGE = 'SAVE_JOIN_MESSAGE';
export const ACCEPT_JOIN_REQUEST_REQUEST = 'ACCEPT_JOIN_REQUEST_REQUEST';
export const ACCEPT_JOIN_REQUEST_SUCCESS = 'ACCEPT_JOIN_REQUEST_SUCCESS';
export const ACCEPT_JOIN_REQUEST_FAIL = 'ACCEPT_JOIN_REQUEST_FAIL';
export const SOCKET_CONNECTION_ERROR = 'SOCKET_CONNECTION_ERROR';
export const SET_JOIN_REQUEST_COUNT = 'SET_JOIN_REQUEST_COUNT';
export const SET_UNREAD_MESSAGE_COUNT = 'SET_UNREAD_MESSAGE_COUNT';
export const CLEAR_USER = 'CLEAR_USER';
export const SET_GENERAL_REQUEST_COUNT = 'SET_GENERAL_REQUEST_COUNT';
export const LOAD_GENERAL_REQUESTS_REQUEST = 'LOAD_GENERAL_REQUESTS_REQUEST';
export const LOAD_GENERAL_REQUESTS_SUCCESS = 'LOAD_GENERAL_REQUESTS_SUCCESS';
export const LOAD_GENERAL_REQUESTS_FAIL = 'LOAD_GENERAL_REQUESTS_FAIL';
export const LOAD_NOTIFICATIONS_REQUEST = 'LOAD_NOTIFICATIONS_REQUEST';
export const LOAD_NOTIFICATIONS_SUCCESS = 'LOAD_NOTIFICATIONS_SUCCESS';
export const LOAD_NOTIFICATIONS_FAIL = 'LOAD_NOTIFICATIONS_FAIL';
export const LIKE_GROUP_REQUEST = "LIKE_GROUP_REQUEST";
export const LIKE_GROUP_SUCCESS = "LIKE_GROUP_SUCCESS";
export const LIKE_GROUP_FAIL = "LIKE_GROUP_FAIL";
export const DISLIKE_GROUP_REQUEST = "DISLIKE_GROUP_REQUEST";
export const DISLIKE_GROUP_SUCCESS = "DISLIKE_GROUP_SUCCESS";
export const DISLIKE_GROUP_FAIL = "DISLIKE_GROUP_FAIL";
export const BOOKMARK_REQUEST = "BOOKMARK_REQUEST";
export const BOOKMARK_SUCCESS = "BOOKMARK_SUCCESS";
export const BOOKMARK_FAIL = "BOOKMARK_FAIL";
export const REMOVE_BOOKMARK_REQUEST = "REMOVE_BOOKMARK_REQUEST";
export const REMOVE_BOOKMARK_SUCCESS = "REMOVE_BOOKMARK_SUCCESS";
export const REMOVE_BOOKMARK_FAIL = "REMOVE_BOOKMARK_FAIL";
export const UPDATE_FOLLOWERS_COUNT = "UPDATE_FOLLOWERS_COUNT";
export const UPDATE_PUBLIC_FOLLOWERS_COUNT = "UPDATE_PUBLIC_FOLLOWERS_COUNT";
export const ACCOMMODATION_REQUEST = "ACCOMMODATION_REQUEST";
export const ACCOMMODATION_SUCCESS = "ACCOMMODATION_SUCCESS";
export const ACCOMMODATION_FAIL = "ACCOMMODATION_FAIL";
export const TRANSPORT_REQUEST = "TRANSPORT_REQUEST";
export const TRANSPORT_SUCCESS = "TRANSPORT_SUCCESS";
export const TRANSPORT_FAIL = "TRANSPORT_FAIL";


export const PREPARE_TO_CREATE = 'PREPARE_TO_CREATE';
export const DISPLAYNAME_TO_CREATE = 'DISPLAYNAME_TO_CREATE';
export const EMAIL_TO_CREATE = 'EMAIL_TO_CREATE';
export const BIRTHDAY_TO_CREATE = 'BIRTHDAY_TO_CREATE';
export const IS_NEW_USER_GOOGLE_LOGIN = 'IS_NEW_USER_GOOGLE_LOGIN';

export const LOAD_USER_BY_ID_REQUEST = 'LOAD_USER_BY_ID_REQUEST';
export const LOAD_USER_BY_ID_SUCCESS = 'LOAD_USER_BY_ID_SUCCESS';
export const LOAD_USER_BY_ID_FAIL = 'LOAD_USER_BY_ID_FAIL';

export const SAVE_DRAFT = 'SAVE_DRAFT';
export const SAVE_DRAFT_SUCCESS = 'SAVE_DRAFT_SUCCESS';
export const SAVE_DRAFT_FAIL = 'SAVE_DRAFT_FAIL';

export const UPDATE_DRAFT = 'UPDATE_DRAFT';
export const UPDATE_DRAFT_SUCCESS = 'UPDATE_DRAFT_SUCCESS';
export const UPDATE_DRAFT_FAIL = 'UPDATE_DRAFT_FAIL';

export const LOAD_DRAFT_BY_USER = 'LOAD_DRAFT_BY_USER';
export const LOAD_DRAFT_BY_USER_SUCCESS = 'LOAD_DRAFT_BY_USER_SUCCESS';
export const LOAD_DRAFT_BY_USER_FAIL = 'LOAD_DRAFT_BY_USER_FAIL';
export const LOAD_DRAFT_BY_USER_SUCCESS_GROUP = 'LOAD_DRAFT_BY_USER_SUCCESS_GROUP';

export const DELETE_DRAFT = 'DELETE_DRAFT';
export const DELETE_DRAFT_SUCCESS = 'DELETE_DRAFT_SUCCESS';
export const DELETE_DRAFT_FAIL = 'DELETE_DRAFT_FAIL';

export const FETCH_THUMBNAILS_REQUEST = 'FETCH_THUMBNAILS_REQUEST';
export const FETCH_THUMBNAILS_SUCCESS = 'FETCH_THUMBNAILS_SUCCESS';
export const FETCH_THUMBNAILS_FAIL = 'FETCH_THUMBNAILS_FAIL';

export const FETCH_DESTINY_REQUEST = 'FETCH_DESTINY_REQUEST';
export const FETCH_DESTINY_SUCCESS = 'FETCH_DESTINY_SUCCESS';
export const FETCH_DESTINY_FAIL = 'FETCH_DESTINY_FAIL';

export const COMMENT_REQUEST = 'COMMENT_REQUEST';
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS';
export const COMMENT_FAIL = 'COMMENT_FAIL';
export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAIL = 'GET_COMMENTS_FAIL';
export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';

//DASHBOARD
export const GET_DESTINATIONS_BY_SEASON_REQUEST = 'GET_DESTINATIONS_BY_SEASON_REQUEST';
export const GET_DESTINATIONS_BY_SEASON_SUCCESS = 'GET_DESTINATIONS_BY_SEASON_SUCCESS';
export const GET_DESTINATIONS_BY_SEASON_FAIL = 'GET_DESTINATIONS_BY_SEASON_FAIL';

export const GET_ALL_DESTINATIONS_WITH_FLAGS_REQUEST = 'GET_ALL_DESTINATIONS_WITH_FLAGS_REQUEST';
export const GET_ALL_DESTINATIONS_WITH_FLAGS_SUCCESS = 'GET_ALL_DESTINATIONS_WITH_FLAGS_SUCCESS';
export const GET_ALL_DESTINATIONS_WITH_FLAGS_FAIL = 'GET_ALL_DESTINATIONS_WITH_FLAGS_FAIL';

export const GET_DESTINATIONS_BY_FEATURED_REQUEST = 'GET_DESTINATIONS_BY_FEATURED_REQUEST';
export const GET_DESTINATIONS_BY_FEATURED_SUCCESS = 'GET_DESTINATIONS_BY_FEATURED_SUCCESS';
export const GET_DESTINATIONS_BY_FEATURED_FAIL = 'GET_DESTINATIONS_BY_FEATURED_FAIL';

export const GET_DESTINATIONS_BY_HAUNTED_REQUEST = 'GET_DESTINATIONS_BY_HAUNTED_REQUEST';
export const GET_DESTINATIONS_BY_HAUNTED_SUCCESS = 'GET_DESTINATIONS_BY_HAUNTED_SUCCESS';
export const GET_DESTINATIONS_BY_HAUNTED_FAIL = 'GET_DESTINATIONS_BY_HAUNTED_FAIL';

export const GET_DESTINATIONS_BY_AMAZING_REQUEST = 'GET_DESTINATIONS_BY_AMAZING_REQUEST';
export const GET_DESTINATIONS_BY_AMAZING_SUCCESS = 'GET_DESTINATIONS_BY_AMAZING_SUCCESS';
export const GET_DESTINATIONS_BY_AMAZING_FAIL = 'GET_DESTINATIONS_BY_AMAZING_FAIL';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';

export const FETCH_CATEGORY_REQUEST = 'FETCH_CATEGORY_REQUEST';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_FAIL = 'FETCH_CATEGORY_FAIL';

export const UPLOAD_IMAGES = 'UPLOAD_IMAGES';
export const UPLOAD_IMAGES_SUCCESS = 'UPLOAD_IMAGES_SUCCESS';
export const UPLOAD_IMAGES_FAIL = 'UPLOAD_IMAGES_FAIL';

export const GENRE_TO_CREATE = 'GENRE_TO_CREATE';

export const SET_SOCKET = 'SET_SOCKET';
export const CLOSE_SOCKET = 'CLOSE_SOCKET';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
export const UPDATE_MESSAGE_ID = 'UPDATE_MESSAGE_ID';
